pipeline {
  agent { any }
  stages {
		stage ('Get Source') {
			steps {
				git 'https://github.com/Michael-Masas/bakery-01/tree/terraform-ec2/Michael-Masas/terraform-ec2'
						}
					}
				}
			}	
		

