pipeline {
agent any
  stages {
    stage('Create Source') {
      steps {
        sh 'rm -rf /tmp/source && cd /tmp && mkdir source'
        sh 'cd /tmp/source && git clone "https://github.com/Michael-Masas/bakery-01.git"'
      }
    }
  }
}
