pipeline {
agent any
  stages {
    stage('Create Source') {
      steps {
        sh 'rm -rf /tmp/source'
        sh 'cd /tmp'
        sh 'mkdir source'
        git "https://github.com/Michael-Masas/bakery-01.git"
      }
    }
  }
}
